name: Deploys Angular application to firebase

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Deploy app to firebase
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build:prod
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
